// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk_QrhVt5tV5H35ogvbmRanOh_nLw873M',
    appId: '1:738141095855:web:fc326e8d5089cb8003115a',
    messagingSenderId: '738141095855',
    projectId: 'skripsi-it',
    authDomain: 'skripsi-it.firebaseapp.com',
    storageBucket: 'skripsi-it.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtjqrW_6khnk_sZsMPHqjJfou8vE-9TiQ',
    appId: '1:738141095855:android:8716ea9b9db3895603115a',
    messagingSenderId: '738141095855',
    projectId: 'skripsi-it',
    storageBucket: 'skripsi-it.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2OMfqexTVqD7D06GcAIs2iN6Sk337RRY',
    appId: '1:738141095855:ios:b308e53a4f3033a003115a',
    messagingSenderId: '738141095855',
    projectId: 'skripsi-it',
    storageBucket: 'skripsi-it.appspot.com',
    iosBundleId: 'com.example.flutterQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2OMfqexTVqD7D06GcAIs2iN6Sk337RRY',
    appId: '1:738141095855:ios:b308e53a4f3033a003115a',
    messagingSenderId: '738141095855',
    projectId: 'skripsi-it',
    storageBucket: 'skripsi-it.appspot.com',
    iosBundleId: 'com.example.flutterQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk_QrhVt5tV5H35ogvbmRanOh_nLw873M',
    appId: '1:738141095855:web:09973256e52a9e1a03115a',
    messagingSenderId: '738141095855',
    projectId: 'skripsi-it',
    authDomain: 'skripsi-it.firebaseapp.com',
    storageBucket: 'skripsi-it.appspot.com',
  );
}
